### ISSUE TITLE
Error while calculating PieAPP score for Set5 image dataset 

### ISSUE THREAD

**Issue by HeenaDabbu** [prashnani/PerceptualImageError#3]
InvalidArgumentError (see above for traceback): Computed output size would be negative: -1 [input_size: 0, effective_filter_size: 64, stride: 27]
	 [[Node: ExtractImagePatches_1 = ExtractImagePatches[T=DT_FLOAT, ksizes=[1, 64, 64, 1], padding="VALID", rates=[1, 1, 1, 1], strides=[1, 27, 27, 1], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_1_0_1)]]

**Comment by HeenaDabbu** [comment]
I got this error when my testing image size is less then 512*512.

**Comment by prashnani** [comment]
thanks for raising the error. @HeenaDabbu ! I fixed the scripts and they should be working with Set5 now. Please pull the latest version and if it looks alright, please close this issue. Thanks!

**Comment by prashnani** [comment]
The issue has been addressed. Closing due to no further comments.
