### ISSUE TITLE
Is the proposed data set still planned for release?

### ISSUE THREAD

**Issue by JasonGUTU** [prashnani/PerceptualImageError#7]
This paper proposes a new dataset and the paper is published in 2018. However, today is around 2020. Is the proposed data set still planned for release? It will be a great contribution to this field and please release the dataset.

**Comment by prashnani** [comment]
thanks for your question @JasonGUTU ! The proposed data is still definitely planned for a release as promised in the original paper. We are working to ensure we abide by all copyright and usage conditions before releasing the dataset and we will release the dataset soon.

**Comment by JasonGUTU** [comment]
> thanks for your question @JasonGUTU ! The proposed data is still definitely planned for a release as promised in the original paper. We are working to ensure we abide by all copyright and usage conditions before releasing the dataset and we will release the dataset soon.

Thank you for your kind reply. this is a great work and I believe that we all looking forward the dataset~

**Comment by prashnani** [comment]
my pleasure! I will post another update on this issue in the next few weeks when the dataset is finally released.

**Comment by zakajd** [comment]
I'm also interested in this dataset. It can really help other researches in this area.

**Comment by prashnani** [comment]
@zakajd thanks for your message - we are actively working to release the dataset soon.

**Comment by prashnani** [comment]
Reopening this issue to let the users know that the PieAPP dataset is now in beta release. Please try it out -- any feedback on improving the release is welcome! @JasonGUTU @zakajd

**Comment by prashnani** [comment]
closing the issue for now - the initial dataset release is good to go.
