### ISSUE TITLE
Simplified implementation

### ISSUE THREAD

**Issue by zakajd** [prashnani/PerceptualImageError#8]
Hi!

I recently re-written your PyTorch implementation and added it to the [PyTorch Image Quality](https://github.com/photosynthesis-team/piq) library.

It's interface is simpler, so if anyone needs PieAPP to inference a batch of images and get their scores, feel free to use it.
https://github.com/photosynthesis-team/piq/pull/184

**Comment by prashnani** [comment]
thanks for the note, @zakajd !! :)
