### ISSUE TITLE
Cannot download a PyTorch model

### ISSUE THREAD

**Issue by fujibo** [prashnani/PerceptualImageError#9]
I execute the following command, but cannot download the weights of a pre-trained model.
```bash
bash scripts/download_PieAPPv0.1_PT_weights.sh
```

The weights seems to be missing from https://web.ece.ucsb.edu/~ekta/projects/PieAPPv0.1/weights/PieAPPv0.1.pth.

**Comment by prashnani** [comment]
sorry about that - the weights should be restored now.
